### ISSUE TITLE
Accordion Submenu not displayed correctly / Title-bar

### ISSUE THREAD

**Issue by thomas529** [JeremyEnglert/JointsWP#165]
Hey,

I noticed that the title bar menu seems to be 'broken'. 

If I load the theme on a small screen (or a small browser window) and extend the submenu, the submenu is displayed horizontally:
![direct load](https://cloud.githubusercontent.com/assets/5512313/13054802/dca61d48-d40b-11e5-8912-21d8820bba04.png)

If I load the same page in a large window, resize the window below the small breakpoint, the submenu is display vertically (as expected).
![resize](https://cloud.githubusercontent.com/assets/5512313/13054849/17b2e664-d40c-11e5-9690-080f15d25b50.png)

It seems to be a problem somewhere around .menu.vertical > li { display: block }. If loaded in a small window the display property is set to table-cell. I tried tracking it don't but couldn't find anything. Working around the problem and adding "vertical" to the menu walker helped, but surely isn't "the solution".

Tested in safari and chrome on mac.

Anybody else got any ideas?

thanks in advance

**Comment by JeremyEnglert** [comment]
This seems like a Foundation bug. I would try submitting it here: https://github.com/zurb/foundation-sites

I know they're making some changes to the menu. They should be able to let you know if there is a fix available for this.

**Comment by thomas529** [comment]
I'll post it there and will post again here if there's an answer.

thanks

**Comment by JeremyEnglert** [comment]
Great! I'll keep an eye on your new post as well. Thanks for reporting this!

**Comment by thomas529** [comment]
No problem. Great theme by the way!

**Comment by thomas529** [comment]
Okay, tested it with a "vanilla" foundation install. Works fine. It seems that the problem exists only in jointswp. 

I also made a fresh install of jointswp without any modifications. Still the same problem.

you can test it here:
http://client.thomasjones.biz/af
user: joints
pass: wordpress

**Comment by JeremyEnglert** [comment]
On line 6 in assets/functions/menu-walkers.php, add the "vertical" class, like this:

```
class Topbar_Menu_Walker extends Walker_Nav_Menu {
    function start_lvl(&$output, $depth = 0, $args = Array() ) {
        $indent = str_repeat("\t", $depth);
        $output .= "\n$indent<ul class=\"vertical menu\">\n";
    }
}
```
