### ISSUE TITLE
$content_width Not Set

### ISSUE THREAD

**Issue by bpongvh** [JeremyEnglert/JointsWP#179]
Really curious to me, but I'm finding $content_width not getting set. I have not yet been able to troubleshoot if other stuff in joints_theme_support() is running correctly. From what I can tell, joints_start() is running properly. If I move the $content_width declaration to the bottom of functions.php, it works correctly.

I haven't really got into this as I could blow a few hours running debuggers. For now I can bail on this issue and move on to other stuff I must finish. I'll try to get back to it and focus if you don't have a quick solution.

**Comment by JeremyEnglert** [comment]
This is really weird for sure. I used Theme Check to see if it threw an error for content_width - but it didn't. However, another user noticed this issue as well: https://github.com/JeremyEnglert/JointsWP/commit/c03adbc4278b186465a3ac74e0cda8af9eb32848#commitcomment-16553229

**Comment by JeremyEnglert** [comment]
This has been fixed.

https://github.com/JeremyEnglert/JointsWP/commit/dabcd63e0a38496e0dbd9f264a05d49a79e8729b

joints_theme_support wasn't being initialized. Oddly enough, some functions inside of it still worked without being called.

**Comment by JeremyEnglert** [comment]
Actually, I'm not 100% confident the above fixed this. Reopening.

**Comment by bpongvh** [comment]
I tried a few different ways to fire off joints_theme_support, and none seemed to pick up $content_width. By now, I'm pretty sure other stuff in there is getting read correctly. I just setup a bunch of new image sizes in there yesterday. I had a funny thought that WP for some stupid reason may only read $content_width from functions.php. I can't think of a good reason for that to be true, but, still being a newbie in WP, the system sometimes does things that mystify me. Anyway, I'll look into this a little more this evening (SE Asia) time :)

Cheers,
Robert

**Comment by Warkman** [comment]
> $content_width from functions.php
I was thinking the same.

**Comment by Warkman** [comment]
Hi @JeremyEnglert I tried with your updated files though did not resolve the issue.

**Comment by Warkman** [comment]
This fixed the issue: Copied the below from  https://github.com/Automattic/_s/blob/master/functions.php
	
	```
function _s_content_width() {
	$GLOBALS['content_width'] = apply_filters( '_s_content_width', 640 );
}
add_action( 'after_setup_theme', '_s_content_width', 0 );	
```

Deleted: 
```
// Set the maximum allowed width for any content in the theme, like oEmbeds and images added to posts.
	if ( ! isset( $content_width ) ) {
		$content_width = 1200; // Default Foundation width
	}	
```

**Comment by bpongvh** [comment]
@Warkman Great find!

Funny, but I was right behind you when your email came in. I had come across discussions about $content_width in _s and the twentysixteen theme:

https://core.trac.wordpress.org/ticket/27863

Here's the function from twentysixteen:

```
/**
 * Sets the content width in pixels, based on the theme's design and stylesheet.
 *
 * Priority 0 to make it available to lower priority callbacks.
 *
 * @global int $content_width
 *
 * @since Twenty Sixteen 1.0
 */
function twentysixteen_content_width() {
	$GLOBALS['content_width'] = apply_filters( 'twentysixteen_content_width', 840 );
}
add_action( 'after_setup_theme', 'twentysixteen_content_width', 0 );
```

I just tested it in theme-support.php, and it works correctly for me. For JointsWP, I think we only need to have the single line assigning `$GLOBALS['content_width']`. The function wrapper is not necessary since theme support is already wrapped in `joints_theme_support()` and hooked to `after_setup_theme` in cleanup.php.

From what I can see, mystery solved!

Cheers,
Robert

**Comment by JeremyEnglert** [comment]
Big thanks @bpongvh and @Warkman!

This did the trick: `$GLOBALS['content_width'] = apply_filters( 'joints_theme_support', 1200 );`

The fix has been merged in: https://github.com/JeremyEnglert/JointsWP/commit/c23ad8f789063f7c55e6ac1ed4dd40b199389e4d
